services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/web/Dockerfile
    volumes:
      - ./web:/app
    ports:
      - "10000:10000"
    restart: always
  
  api:
    build:
      context: .
      dockerfile: .devcontainer/api/Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "10001:10001"
    restart: always

  redis:
    image: redis:latest
    volumes:
      - ./web:/data
    
  s3mock:
    image: adobe/s3mock:latest
    environment:
      - initialBuckets=bucket1
      - debug=true
      - retainFilesOnExit=true
      - root=containers3root
    ports:
      - 9090:9090
    volumes:
      - ./locals3root:/containers3root